defaults:
  - dataset: [Objaverse, MVImgNet, RealEstate10K] # DL3DV10K
  - dataloader:
  - model: "model"
  - loss: [point_distribution_loss, denoising_loss, novel_view_loss]

wandb:
  entity: conple21
  project: DiffusionGS
  name: Experiment1
  mode: online

mode: train

dataset:
  name: MVImgNet
  path: outputs
  image_shape: [180, 320]
  remove_background: True
  center_and_scale: True
  root: datasets/MVImgNet
  max_fov: 50.
  u_near: 0.1
  u_far: 4.2
  view_sampler:
    name: "view_sampler"
    num_clean_views: 1
    num_noisy_views: 3
    theta1: 90.
    theta2: 90.
    phi1: 90.
    phi2: 90.

dataloader:
  train:
    batch_size: 1
    num_workers: 0
    seed: 1234
  test:
    batch_size: 1
    num_workers: 0
    seed: 1234
  validation:
    batch_size: 1
    num_workers: 0
    seed: 1234

model:
  diffusion:
    model_id: "ptx0/pseudo-journey-v2"
    timestep_spacing: "trailing"
    total_timesteps: 101
    num_timesteps: 1
  timestep:
    name: "timestep_mlp"
    embedding:
      name: "timestep_embedding"
      time_dim: 128
      max_period: 10_000
    out_dim: 768
  patchify:
    name: "patch_mlp"
    embedding:
      in_channels: 3
      patch_size: 16
      embedding_dim: 768
    out_dim: 768
  positional:
    name: "positional_embedding"
    num_patches: 16
    embedding_dim: 512
  backbone:
    name: "transformer_backbone"
    layer:
      name: "transformer_backbone_layer"
      timestep_mlp:
        name: "timestep_mlp"
        embedding:
          name: "timestep_embedding"
          time_dim: 128
          max_period: 10_000
        out_dim: 768
      attention_dim: 512
      num_heads: 8
      dropout: 0.1
    num_layers: 6
  object_decoder:
    name: "object_decoder"
    u_near: 0.1
    u_far: 4.2
    input_dim: 768
    hidden_dim: 768
    output_dim: 14
    weight: 0.5
    num_points: 8192
    timestep_mlp:
      name: "timestep_mlp"
      embedding:
        name: "timestep_embedding"
        time_dim: 128
        max_period: 10_000
      out_dim: 768
  scene_decoder:
    name: scene_decoder
    u_near: 0.
    u_far: 500.
    input_dim: 768
    hidden_dim: 768
    output_dim: 14
    weight: 0.5
    num_points: 8192
    timestep_mlp:
      name: "timestep_mlp"
      embedding:
        name: "timestep_embedding"
        time_dim: 128
        max_period: 10_000
      out_dim: 768
  render:
    sh_degree: 3
    scale_modifier: 1.
    prefiltered: False
    debug: False

optimizer:
  learning_rate: 4e-4
  total_steps: 40_000
  warmup_steps: 2_000

checkpoint:
  load: null
  every_num_timesteps: 5000
  save_top_k: -1

trainer:
  max_steps: -1
  precision: 16
  validation_check_interval: 0
  gradient_clip_validation: 0.5

losses:
  denoising:
    name: "DenoisingLoss"
    weight: 0.8
  novel_view:
    name: "NovelViewLoss"
    weight: 0.8
  point_distribution:
    name: "PointDistributionLoss"
    sigma_0: 0.5

train:
  is_object_dataset: True

test:
  output_path: "outputs/test"

seed: 12


